// <auto-generated />
using System;
using CompraAutomatizada.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CompraAutomatizada.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260305005513_AddClienteIdToDistribuicao")]
    partial class AddClienteIdToDistribuicao
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.CestaTopFiveAggregate.CestaTopFive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataDesativacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("CestasRecomendacao", (string)null);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.CestaTopFiveAggregate.ItemCesta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("CestaId")
                        .HasColumnType("bigint");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("CestaId");

                    b.ToTable("ItensCesta", (string)null);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.ClienteAggregate.Cliente", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataAdesao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<decimal>("ValorMensal")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Clientes", (string)null);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.ContaGraficaAggregate.ContaGrafica", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<long?>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NumeroConta")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClienteId")
                        .IsUnique();

                    b.HasIndex("NumeroConta")
                        .IsUnique();

                    b.ToTable("ContasGraficas", (string)null);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.ContaGraficaAggregate.Custodia", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaGraficaId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataUltimaAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedio")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ContaGraficaId", "Ticker")
                        .IsUnique();

                    b.ToTable("Custodias", (string)null);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.CotacaoAggregate.Cotacao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateOnly>("DataPregao")
                        .HasColumnType("date");

                    b.Property<decimal>("PrecoAbertura")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoFechamento")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoMaximo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("PrecoMinimo")
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<long>("VolumeNegociado")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Ticker", "DataPregao")
                        .IsUnique();

                    b.ToTable("Cotacoes", (string)null);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.EventoIRAggregate.EventoIR", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataEvento")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal?>("LucroLiquido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("PublicadoKafka")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.Property<decimal>("ValorIr")
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("ValorOperacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("EventosIR", (string)null);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.OrdemAggregate.Distribuicao", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<long>("CustodiaFilhoteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataDistribuicao")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("OrdemCompraId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<decimal>("ValorIrDedoDuro")
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("OrdemCompraId");

                    b.ToTable("Distribuicoes", (string)null);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.OrdemAggregate.OrdemDeCompra", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ContaMasterId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataExecucao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("TipoMercado")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("OrdensCompra", (string)null);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.RebalanceamentoAggregate.Rebalanceamento", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("ClienteId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("DataRebalanceamento")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("QuantidadeComprada")
                        .HasColumnType("int");

                    b.Property<int>("QuantidadeVendida")
                        .HasColumnType("int");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<decimal?>("ValorIrApurado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorTotalVendas")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Rebalanceamentos", (string)null);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.CestaTopFiveAggregate.ItemCesta", b =>
                {
                    b.HasOne("CompraAutomatizada.Domain.Aggregates.CestaTopFiveAggregate.CestaTopFive", null)
                        .WithMany("Itens")
                        .HasForeignKey("CestaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("CompraAutomatizada.Domain.ValueObjects.Proporcao", "Percentual", b1 =>
                        {
                            b1.Property<long>("ItemCestaId")
                                .HasColumnType("bigint");

                            b1.Property<decimal>("Valor")
                                .HasColumnType("decimal(5,2)")
                                .HasColumnName("Percentual");

                            b1.HasKey("ItemCestaId");

                            b1.ToTable("ItensCesta");

                            b1.WithOwner()
                                .HasForeignKey("ItemCestaId");
                        });

                    b.Navigation("Percentual")
                        .IsRequired();
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.ClienteAggregate.Cliente", b =>
                {
                    b.OwnsOne("CompraAutomatizada.Domain.ValueObjects.Cpf", "Cpf", b1 =>
                        {
                            b1.Property<long>("ClienteId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Valor")
                                .IsRequired()
                                .HasMaxLength(11)
                                .HasColumnType("varchar(11)")
                                .HasColumnName("CPF");

                            b1.HasKey("ClienteId");

                            b1.HasIndex("Valor")
                                .IsUnique();

                            b1.ToTable("Clientes");

                            b1.WithOwner()
                                .HasForeignKey("ClienteId");
                        });

                    b.Navigation("Cpf")
                        .IsRequired();
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.ContaGraficaAggregate.ContaGrafica", b =>
                {
                    b.HasOne("CompraAutomatizada.Domain.Aggregates.ClienteAggregate.Cliente", null)
                        .WithOne("Conta")
                        .HasForeignKey("CompraAutomatizada.Domain.Aggregates.ContaGraficaAggregate.ContaGrafica", "ClienteId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.ContaGraficaAggregate.Custodia", b =>
                {
                    b.HasOne("CompraAutomatizada.Domain.Aggregates.ContaGraficaAggregate.ContaGrafica", null)
                        .WithMany("Posicoes")
                        .HasForeignKey("ContaGraficaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.OrdemAggregate.Distribuicao", b =>
                {
                    b.HasOne("CompraAutomatizada.Domain.Aggregates.OrdemAggregate.OrdemDeCompra", null)
                        .WithMany("Distribuicoes")
                        .HasForeignKey("OrdemCompraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.CestaTopFiveAggregate.CestaTopFive", b =>
                {
                    b.Navigation("Itens");
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.ClienteAggregate.Cliente", b =>
                {
                    b.Navigation("Conta");
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.ContaGraficaAggregate.ContaGrafica", b =>
                {
                    b.Navigation("Posicoes");
                });

            modelBuilder.Entity("CompraAutomatizada.Domain.Aggregates.OrdemAggregate.OrdemDeCompra", b =>
                {
                    b.Navigation("Distribuicoes");
                });
#pragma warning restore 612, 618
        }
    }
}
